### ISSUE TITLE
Mejorar la carga de los steps

### ISSUE THREAD

**Issue by MranDvX** [EntrevistadorInteligente/landing-entrevistador#39]
Mejorar la carga de los steps siempre muestra el formulario aun cuando el step en el que esta no es el primero. 
Deshabilitar la muestra del stel con un loading hasta que el back responda y allí si se muestran los steps.

![Image](https://github.com/user-attachments/assets/52f72859-8b33-4b69-8424-95abb835fb1b)

![Image](https://github.com/user-attachments/assets/9ae6df98-265a-4e04-afea-1fb1c61a5094)

**Comment by JamiltonQuintero** [comment]
Se resuelve dejando una condicion en la carga del step

![Image](https://github.com/user-attachments/assets/2b29f279-9d89-4a63-82d1-57cd71ebc5b8)


![Image](https://github.com/user-attachments/assets/a9ca9443-7b8c-49ee-8ab2-1cdfaf96114f)
